lowmach_react_hex – LowMachReact-Hex
lowmach_react_hex Program
168 statements
Source File
Uses
mod_mesh_types
mod_bc
mod_mesh_io
mod_flow_projection
mod_output
mod_transport_properties
mod_profiler
mod_input
mod_mpi_flow
mod_mpi_radiation
mod_kinds
mod_species
mpi_f08
mod_fields
Main entry point for the LowMachReact-Hex hexahedral low-Mach FV solver.
This program orchestrates the entire simulation lifecycle: 1. Initialization: Starts MPI, parses the case.nml namelist, and reads the mesh. 2. Domain Decomposition: Sets up the replicated mesh MPI ranks for flow and radiation. 3. Field Setup: Allocates and initializes velocity, pressure, and species mass fractions. 4. Time Integration Loop: Executes the fractional-step projection method and species transport. 5. Diagnostics & Output: Computes global observables and writes VTU/CSV files. 6. Finalization: Safely releases all allocated memory and shuts down MPI.
Calls
Contents
Variables
params mesh flow_mpi rad_mpi bc fields stats species transport case_file step ierr world_rank do_output_step time t0
Subroutines
compute_global_observables get_case_filename
Variables
Type Attributes Name Initial
type(case_params_t) :: params
type(mesh_t) :: mesh
type(flow_mpi_t) :: flow_mpi
type(radiation_mpi_t) :: rad_mpi
type(bc_set_t) :: bc
type(flow_fields_t) :: fields
type(solver_stats_t) :: stats
type(species_fields_t) :: species
type(transport_properties_t) :: transport
character(len=256) :: case_file
integer :: step
integer :: ierr
integer :: world_rank
logical :: do_output_step
real(kind=rk) :: time
real(kind=rk) :: t0
Subroutines
subroutine compute_global_observables(mesh, flow, fields, species, transport, stats)
Computes global integral quantities for diagnostic reporting.
Read more…
Arguments
Type Intent Optional Attributes Name
type(mesh_t), intent(in) :: mesh
type(flow_mpi_t), intent(in) :: flow
type(flow_fields_t), intent(in) :: fields
type(species_fields_t), intent(in) :: species
type(transport_properties_t), intent(in) :: transport
type(solver_stats_t), intent(inout) :: stats
subroutine get_case_filename(filename)
Parses command line arguments to find the case configuration file.
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(out) :: filename
Call graph
lowmach_react_hex calls read_case_params, advance_species_transport, advance_projection_step, compute_and_update_cfl, compute_global_observables, radiation_mpi_finalize, build_bc_set, initialize_species, prepare_output, get_case_filename, profiler_start, profiler_configure, compute_flow_diagnostics, flow_mpi_finalize, mesh_finalize, fatal_error, initialize_transport, mpi_comm_rank, profiler_report, finalize_transport, flow_mpi_initialize, radiation_mpi_initialize, initialize_fields, write_pvd_collection, write_mesh_summary, write_diagnostics_header, mpi_flow_startup, mpi_wtime, read_native_mesh, update_transport_properties, profiler_stop, finalize_fields, finalize_bc_set, mpi_flow_shutdown, finalize_species, write_diagnostics_row, write_vtu_unstructured
advance_species_transport calls boundary_species, face_effective_neighbor, face_normal_distance, flow_exchange_cell_matrix
advance_projection_step calls profiler_start, compute_flow_diagnostics, profiler_stop, flow_exchange_face_scalar, flow_exchange_cell_matrix, rhs_poisson, flow_exchange_cell_scalar
compute_and_update_cfl calls mpi_allreduce
compute_global_observables calls mpi_allreduce
radiation_mpi_finalize calls mpi_comm_free
build_bc_set calls fatal_error, finalize_bc_set, lowercase
initialize_species calls finalize_species, lowercase
prepare_output calls fatal_error
get_case_filename calls fatal_error
profiler_start calls mpi_wtime
profiler_configure calls profiler_reset
compute_flow_diagnostics calls flow_global_max_owned, mpi_allreduce
flow_mpi_finalize calls mpi_comm_free
profiler_report calls mpi_allreduce
flow_mpi_initialize calls flow_mpi_finalize, mpi_comm_rank, mpi_comm_dup, mpi_comm_size
radiation_mpi_initialize calls radiation_mpi_finalize, mpi_comm_rank, mpi_comm_dup, mpi_comm_size, radiation_task_bounds
initialize_fields calls allocate_fields
mpi_flow_startup calls mpi_initialized, mpi_init
read_native_mesh calls mesh_finalize
update_transport_properties calls profiler_start, fatal_error, profiler_stop, flow_exchange_cell_matrix, flow_exchange_cell_scalar
profiler_stop calls mpi_wtime
mpi_flow_shutdown calls mpi_finalize, mpi_finalized
write_vtu_unstructured calls flow_gather_owned_scalar_root, flow_gather_owned_matrix_root
flow_exchange_face_scalar calls profiler_start, profiler_stop, mpi_waitall, mpi_isend, mpi_irecv
allocate_fields calls finalize_fields
flow_gather_owned_scalar_root calls profiler_start, profiler_stop, mpi_gatherv
face_effective_neighbor calls is_periodic_face
flow_gather_owned_matrix_root calls profiler_start, profiler_stop, mpi_gatherv
radiation_task_bounds calls fatal_error
flow_global_max_owned calls profiler_start, profiler_stop, mpi_allreduce
face_normal_distance calls fatal_error, patch_type_for_face
flow_exchange_cell_matrix calls profiler_start, fatal_error, profiler_stop, mpi_waitall, mpi_isend, mpi_irecv
flow_exchange_cell_scalar calls profiler_start, profiler_stop, mpi_waitall, mpi_isend, mpi_irecv
is_periodic_face calls patch_type_for_face