advance_projection_step – LowMachReact-Hex
advance_projection_step Subroutine
83 statements
Source File
public subroutine advance_projection_step(mesh, flow, bc, params, transport, fields, stats)
Orchestrates one full fractional-step iteration.
This routine implements the high-level logic of the projection method. It coordinates the explicit momentum update, the elliptic pressure solve, and the final divergence-free correction.
@param mesh The computational mesh. @param flow MPI decomposition context. @param bc Boundary condition set. @param params Case parameters (dt, rho, etc). @param transport Physical property fields. @param fields Flow field containers to be updated. @param stats Diagnostic stats to be populated.
Arguments
Type Intent Optional Attributes Name
type(mesh_t), intent(in) :: mesh
type(flow_mpi_t), intent(inout) :: flow
type(bc_set_t), intent(in) :: bc
type(case_params_t), intent(in) :: params
type(transport_properties_t), intent(in) :: transport
type(flow_fields_t), intent(inout) :: fields
type(solver_stats_t), intent(inout) :: stats
Calls
Called by
Contents
None
Call graph
advance_projection_step calls profiler_start, profiler_stop, flow_exchange_face_scalar, rhs_poisson, flow_exchange_cell_matrix, flow_exchange_cell_scalar, compute_flow_diagnostics
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime
flow_exchange_face_scalar calls profiler_start, profiler_stop, mpi_waitall, mpi_isend, mpi_irecv
flow_exchange_cell_matrix calls profiler_start, profiler_stop, mpi_waitall, mpi_isend, mpi_irecv, fatal_error
flow_exchange_cell_scalar calls profiler_start, profiler_stop, mpi_waitall, mpi_isend, mpi_irecv
compute_flow_diagnostics calls flow_global_max_owned, mpi_allreduce
flow_global_max_owned calls profiler_start, profiler_stop, mpi_allreduce
lowmach_react_hex calls advance_projection_step