advance_species_transport – LowMachReact-Hex
advance_species_transport Subroutine
86 statements
Source File
public subroutine advance_species_transport(mesh, flow, bc, params, fields, species, transport)
Performs one explicit Euler step for species transport.
This routine evaluates: - Advective Fluxes: $J_{adv,k} = \dot{m}f Y$. - Diffusive Fluxes: $J_{diff,k} = -D_k A_f \nabla Y_k$. - Flux Correction: Subtracts $Y_k \sum J_{diff,k}$ to satisfy mass conservation. - Bounding & Normalization: Clamps $Y_k \in [0, 1]$ and enforces $\sum Y_k = 1$ locally.
@param mesh The computational mesh. @param flow MPI decomposition data for synchronization. @param bc Boundary condition settings. @param params Simulation parameters (dt, etc). @param fields Flow field (velocity/face fluxes). @param species Mass fraction fields to update. @param transport Physical properties (diffusivities).
Arguments
Type Intent Optional Attributes Name
type(mesh_t), intent(in) :: mesh
type(flow_mpi_t), intent(inout) :: flow
type(bc_set_t), intent(in) :: bc
type(case_params_t), intent(in) :: params
type(flow_fields_t), intent(in) :: fields
type(species_fields_t), intent(inout) :: species
type(transport_properties_t), intent(in) :: transport
Calls
Called by
Contents
None
Call graph
advance_species_transport calls face_effective_neighbor, face_normal_distance, boundary_species, flow_exchange_cell_matrix
face_effective_neighbor calls is_periodic_face
face_normal_distance calls patch_type_for_face, fatal_error
flow_exchange_cell_matrix calls profiler_start, mpi_waitall, fatal_error, mpi_isend, mpi_irecv, profiler_stop
is_periodic_face calls patch_type_for_face
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime
lowmach_react_hex calls advance_species_transport