build_bc_set – LowMachReact-Hex
build_bc_set Subroutine
50 statements
Source File
public subroutine build_bc_set(mesh, params, bc)
Synchronizes namelist parameters with mesh patches to create a complete BC set.
This routine iterates through all patches in the mesh_t structure and searches for matching names in the case_params_t object. It converts string-based inputs into internal type IDs.
@param mesh The computational mesh containing patch definitions. @param params Parsed case configuration from case.nml. @param bc The boundary condition set to be populated.
Arguments
Type Intent Optional Attributes Name
type(mesh_t), intent(in) :: mesh
type(case_params_t), intent(in) :: params
type(bc_set_t), intent(inout) :: bc
Calls
Called by
Contents
None
Call graph
build_bc_set calls finalize_bc_set, fatal_error, lowercase
lowmach_react_hex calls build_bc_set