compute_flow_diagnostics – LowMachReact-Hex
compute_flow_diagnostics Subroutine
29 statements
Source File
public subroutine compute_flow_diagnostics(mesh, flow, bc, params, fields, stats)
Aggregates global residuals, kinetic energy, and mass balance data.
Arguments
Type Intent Optional Attributes Name
type(mesh_t), intent(in) :: mesh
type(flow_mpi_t), intent(in) :: flow
type(bc_set_t), intent(in) :: bc
type(case_params_t), intent(in) :: params
type(flow_fields_t), intent(in) :: fields
type(solver_stats_t), intent(inout) :: stats
Calls
Called by
Contents
None
Call graph
compute_flow_diagnostics calls flow_global_max_owned, mpi_allreduce
flow_global_max_owned calls mpi_allreduce, profiler_start, profiler_stop
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime
advance_projection_step calls compute_flow_diagnostics
lowmach_react_hex calls compute_flow_diagnostics, advance_projection_step