fatal_error – LowMachReact-Hex
fatal_error Subroutine
6 statements
Source File
public subroutine fatal_error(scope, message)
Aborts the simulation with a formatted error message.
This routine should be used for unrecoverable errors (e.g., missing input files, converged solver failures). It writes to standard error and calls stop 1.
@param scope The name of the module or feature (e.g., "mod_input"). @param message Descriptive message explaining why the simulation failed.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: scope
character(len=*), intent(in) :: message
Called by
Contents
None
Call graph
build_bc_set calls fatal_error
get_case_filename calls fatal_error
flow_allgather_owned_matrix calls fatal_error
prepare_output calls fatal_error
flow_allgather_owned_scalar calls fatal_error
flow_allgather_owned_v4 calls fatal_error
flow_exchange_cell_matrix calls fatal_error
radiation_task_bounds calls fatal_error
face_normal_distance calls fatal_error
update_transport_properties calls fatal_error, flow_exchange_cell_matrix
lowmach_react_hex calls fatal_error, build_bc_set, get_case_filename, prepare_output, update_transport_properties, advance_species_transport, radiation_mpi_initialize, advance_projection_step
flow_allgather_owned_vector calls flow_allgather_owned_matrix
advance_species_transport calls flow_exchange_cell_matrix, face_normal_distance
radiation_mpi_initialize calls radiation_task_bounds
advance_projection_step calls flow_exchange_cell_matrix