flow_allgather_owned_vector – LowMachReact-Hex
flow_allgather_owned_vector Subroutine
6 statements
Source File
public subroutine flow_allgather_owned_vector(flow, local_global, global)
Gathers locally-updated 3D vector cell values and broadcasts to the global mesh.
This optimized version performs a single MPI_Allgatherv for all 3 components to minimize communication latency.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(inout) :: flow
real(kind=rk), intent(in) :: local_global(:,:)
real(kind=rk), intent(out) :: global(:,:)
Calls
Contents
None
Call graph
flow_allgather_owned_vector calls flow_allgather_owned_matrix
flow_allgather_owned_matrix calls fatal_error, profiler_start, profiler_stop, mpi_allgatherv
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime