flow_global_dot_owned – LowMachReact-Hex
flow_global_dot_owned Function
15 statements
Source File
public function flow_global_dot_owned(flow, a, b) result(dot)
Uses
mod_profiler
Computes the global dot product of two vectors over owned cells.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(in) :: flow
real(kind=rk), intent(in) :: a(:)
real(kind=rk), intent(in) :: b(:)
Return Value real(kind=rk)
Calls
Contents
None
Call graph
flow_global_dot_owned calls profiler_start, mpi_allreduce, profiler_stop