flow_exchange_face_scalar – LowMachReact-Hex
flow_exchange_face_scalar Subroutine
38 statements
Source File
public subroutine flow_exchange_face_scalar(flow, face_field)
Uses
mod_profiler
Exchanges owner-computed face scalar values to ranks owning the neighbor cell.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(inout) :: flow
real(kind=rk), intent(inout) :: face_field(:)
Calls
Called by
Contents
None
Call graph
flow_exchange_face_scalar calls profiler_start, mpi_waitall, mpi_isend, mpi_irecv, profiler_stop
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime
advance_projection_step calls flow_exchange_face_scalar
lowmach_react_hex calls advance_projection_step