flow_allgather_owned_matrix_inplace – LowMachReact-Hex
flow_allgather_owned_matrix_inplace Subroutine
32 statements
Source File
public subroutine flow_allgather_owned_matrix_inplace(flow, field)
Uses
mod_profiler
In-place variant for fields that already hold owned-cell updates.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(inout) :: flow
real(kind=rk), intent(inout) :: field(:,:)
Calls
Contents
None
Call graph
flow_allgather_owned_matrix_inplace calls profiler_start, profiler_stop, mpi_allgatherv
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime