flow_allgather_owned_matrix – LowMachReact-Hex
flow_allgather_owned_matrix Subroutine
36 statements
Source File
public subroutine flow_allgather_owned_matrix(flow, local_global, global)
Uses
mod_profiler
Gathers locally-updated matrix cell values and broadcasts to the global mesh.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(inout) :: flow
real(kind=rk), intent(in) :: local_global(:,:)
real(kind=rk), intent(out) :: global(:,:)
Calls
Called by
Contents
None
Call graph
flow_allgather_owned_matrix calls fatal_error, profiler_start, profiler_stop, mpi_allgatherv
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime
flow_allgather_owned_vector calls flow_allgather_owned_matrix