flow_allreduce_global_scalar – LowMachReact-Hex
flow_allreduce_global_scalar Subroutine
11 statements
Source File
public subroutine flow_allreduce_global_scalar(flow, local_values, global_values)
Uses
mod_profiler
Sum-Allreduce for a global scalar field.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(in) :: flow
real(kind=rk), intent(in) :: local_values(:)
real(kind=rk), intent(out) :: global_values(:)
Calls
Called by
Contents
None
Call graph
flow_allreduce_global_scalar calls profiler_start, mpi_allreduce, profiler_stop
advance_projection_step calls flow_allreduce_global_scalar
lowmach_react_hex calls advance_projection_step