flow_exchange_cell_matrix – LowMachReact-Hex
flow_exchange_cell_matrix Subroutine
48 statements
Source File
public subroutine flow_exchange_cell_matrix(flow, field)
Uses
mod_profiler
Exchanges owned cell matrix values to ranks that keep them as ghosts.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(inout) :: flow
real(kind=rk), intent(inout) :: field(:,:)
Calls
Called by
Contents
None
Call graph
flow_exchange_cell_matrix calls fatal_error, profiler_start, mpi_waitall, mpi_isend, mpi_irecv, profiler_stop
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime
advance_species_transport calls flow_exchange_cell_matrix
update_transport_properties calls flow_exchange_cell_matrix
advance_projection_step calls flow_exchange_cell_matrix
lowmach_react_hex calls advance_species_transport, update_transport_properties, advance_projection_step