flow_global_max_owned – LowMachReact-Hex
flow_global_max_owned Function
19 statements
Source File
public function flow_global_max_owned(flow, a) result(global_max)
Uses
mod_profiler
Computes the global maximum magnitude of a field over owned cells.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(in) :: flow
real(kind=rk), intent(in) :: a(:)
Return Value real(kind=rk)
Calls
Called by
Contents
None
Call graph
flow_global_max_owned calls profiler_start, mpi_allreduce, profiler_stop
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime
compute_flow_diagnostics calls flow_global_max_owned
advance_projection_step calls compute_flow_diagnostics
lowmach_react_hex calls compute_flow_diagnostics, advance_projection_step