flow_allgather_owned_v4 – LowMachReact-Hex
flow_allgather_owned_v4 Subroutine
34 statements
Source File
public subroutine flow_allgather_owned_v4(flow, local_v, local_s, global_v, global_s)
Uses
mod_profiler
Gathers 4-component cell values (e.g., Velocity + Scalar) in one call.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(inout) :: flow
real(kind=rk), intent(in) :: local_v(:,:)
real(kind=rk), intent(in) :: local_s(:)
real(kind=rk), intent(out) :: global_v(:,:)
real(kind=rk), intent(out) :: global_s(:)
Calls
Contents
None
Call graph
flow_allgather_owned_v4 calls fatal_error, profiler_start, profiler_stop, mpi_allgatherv
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime