flow_global_sum_owned – LowMachReact-Hex
flow_global_sum_owned Function
19 statements
Source File
public function flow_global_sum_owned(flow, a) result(total)
Uses
mod_profiler
Computes the global sum of a field over owned cells.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(in) :: flow
real(kind=rk), intent(in) :: a(:)
Return Value real(kind=rk)
Calls
Contents
None
Call graph
flow_global_sum_owned calls profiler_start, mpi_allreduce, profiler_stop
profiler_start calls mpi_wtime
profiler_stop calls mpi_wtime