flow_mpi_initialize – LowMachReact-Hex
flow_mpi_initialize Subroutine
38 statements
Source File
public subroutine flow_mpi_initialize(mesh, flow, comm_parent, max_gather_components)
Sets up domain decomposition for a given mesh.
Splits the total number of cells among available processors using a contiguous block decomposition.
@param mesh The mesh to decompose. @param flow The MPI context to populate. @param comm_parent The parent communicator (usually MPI_COMM_WORLD).
Arguments
Type Intent Optional Attributes Name
type(mesh_t), intent(in) :: mesh
type(flow_mpi_t), intent(inout) :: flow
type(MPI_Comm), intent(in) :: comm_parent
integer, intent(in), optional :: max_gather_components
Calls
Called by
Contents
None
Call graph
flow_mpi_initialize calls flow_mpi_finalize, mpi_comm_dup, mpi_comm_size, mpi_comm_rank
flow_mpi_finalize calls mpi_comm_free
lowmach_react_hex calls flow_mpi_initialize