flow_allreduce_global_vector – LowMachReact-Hex
flow_allreduce_global_vector Subroutine
11 statements
Source File
public subroutine flow_allreduce_global_vector(flow, local_values, global_values)
Uses
mod_profiler
Sum-Allreduce for a 3D global vector field.
Arguments
Type Intent Optional Attributes Name
type(flow_mpi_t), intent(in) :: flow
real(kind=rk), intent(in) :: local_values(:,:)
real(kind=rk), intent(out) :: global_values(:,:)
Calls
Contents
None
Call graph
flow_allreduce_global_vector calls profiler_start, mpi_allreduce, profiler_stop