patch_type_for_face – LowMachReact-Hex
patch_type_for_face Function
12 statements
Source File
public function patch_type_for_face(mesh, bc, face_id) result(type_id)
Arguments
Type Intent Optional Attributes Name
type(mesh_t), intent(in) :: mesh
type(bc_set_t), intent(in) :: bc
integer, intent(in) :: face_id
Return Value integer
Called by
Contents
None
Call graph
is_periodic_face calls patch_type_for_face
face_normal_distance calls patch_type_for_face
face_effective_neighbor calls is_periodic_face
advance_species_transport calls face_normal_distance, face_effective_neighbor
lowmach_react_hex calls advance_species_transport