profiler_start – LowMachReact-Hex
profiler_start Subroutine
13 statements
Source File
public subroutine profiler_start(name)
Starts a timer for a named kernel.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Calls
Called by
Contents
None
Call graph
profiler_start calls mpi_wtime
flow_allgather_owned_v4 calls profiler_start
flow_gather_owned_scalar_root calls profiler_start
flow_global_sum_owned calls profiler_start
advance_projection_step calls profiler_start, flow_exchange_face_scalar, flow_exchange_cell_scalar, flow_exchange_cell_matrix, compute_flow_diagnostics
flow_allreduce_global_scalar calls profiler_start
flow_allgather_owned_matrix calls profiler_start
flow_global_two_dots_owned calls profiler_start
flow_exchange_face_scalar calls profiler_start
update_transport_properties calls profiler_start, flow_exchange_cell_scalar, flow_exchange_cell_matrix
lowmach_react_hex calls profiler_start, advance_projection_step, update_transport_properties, write_vtu_unstructured, compute_flow_diagnostics, advance_species_transport
flow_gather_owned_matrix_root calls profiler_start
flow_exchange_cell_scalar calls profiler_start
flow_allgather_owned_scalar calls profiler_start
flow_allgather_owned_matrix_inplace calls profiler_start
flow_global_dots_owned calls profiler_start
flow_global_max_owned calls profiler_start
flow_exchange_cell_matrix calls profiler_start
flow_allreduce_global_vector calls profiler_start
flow_global_dot_owned calls profiler_start
write_vtu_unstructured calls flow_gather_owned_scalar_root, flow_gather_owned_matrix_root
compute_flow_diagnostics calls flow_global_max_owned
flow_allgather_owned_vector calls flow_allgather_owned_matrix
advance_species_transport calls flow_exchange_cell_matrix