radiation_mpi_finalize – LowMachReact-Hex
radiation_mpi_finalize Subroutine
14 statements
Source File
public subroutine radiation_mpi_finalize(rad)
Releases radiation MPI resources.
Arguments
Type Intent Optional Attributes Name
type(radiation_mpi_t), intent(inout) :: rad
Calls
Called by
Contents
None
Call graph
radiation_mpi_finalize calls mpi_comm_free
radiation_mpi_initialize calls radiation_mpi_finalize
lowmach_react_hex calls radiation_mpi_finalize, radiation_mpi_initialize