radiation_mpi_initialize – LowMachReact-Hex
radiation_mpi_initialize Subroutine
16 statements
Source File
public subroutine radiation_mpi_initialize(rad, comm_parent, n_tasks)
Initializes the radiation MPI context by duplicating a parent communicator.
@param rad The radiation context to initialize. @param comm_parent The parent communicator (usually MPI_COMM_WORLD). @param n_tasks Optional total number of tasks to decompose immediately.
Arguments
Type Intent Optional Attributes Name
type(radiation_mpi_t), intent(inout) :: rad
type(MPI_Comm), intent(in) :: comm_parent
integer, intent(in), optional :: n_tasks
Calls
Called by
Contents
None
Call graph
radiation_mpi_initialize calls radiation_mpi_finalize, mpi_comm_dup, mpi_comm_size, mpi_comm_rank, radiation_task_bounds
radiation_mpi_finalize calls mpi_comm_free
radiation_task_bounds calls fatal_error
lowmach_react_hex calls radiation_mpi_initialize