update_transport_properties – LowMachReact-Hex
update_transport_properties Subroutine
108 statements
Source File
public subroutine update_transport_properties(mesh, flow, params, Y, transport)
Uses
iso_c_binding
mod_profiler
Evaluates physical properties for the entire domain.
If Cantera is enabled, it calls the C++ bridge to calculate mixture-averaged viscosity and diffusivity. Otherwise, it applies the uniform constant values defined in params.
@param mesh The computational mesh. @param flow MPI decomposition and halo metadata. @param params Simulation parameters and background conditions. @param Y Optional input mass fractions (ncells, nspecies). @param transport The property container to update.
Arguments
Type Intent Optional Attributes Name
type(mesh_t), intent(in) :: mesh
type(flow_mpi_t), intent(inout) :: flow
type(case_params_t), intent(in) :: params
real(kind=rk), intent(in), optional :: Y(:,:)
type(transport_properties_t), intent(inout) :: transport
Calls
Called by
Contents
None
Call graph
update_transport_properties calls fatal_error, profiler_start, flow_exchange_cell_scalar, profiler_stop, flow_exchange_cell_matrix
profiler_start calls mpi_wtime
flow_exchange_cell_scalar calls profiler_start, profiler_stop, mpi_waitall, mpi_isend, mpi_irecv
profiler_stop calls mpi_wtime
flow_exchange_cell_matrix calls fatal_error, profiler_start, profiler_stop, mpi_waitall, mpi_isend, mpi_irecv
lowmach_react_hex calls update_transport_properties